[iface]
name = "tun0"
mtu = 1360
address = "10.0.0.1"
mask = "255.255.255.0"
disable_on_exit = false

[client]
tunnels = ["tls"]
nodes = 2

[[nodes]]
id = "50051_tls"
addr = "0.0.0.0:50051"
ca = "certs/ca.pem"
sni = "localhost"
tunnel = "tls"

[[nodes]]
id = "50052_tls"
addr = "0.0.0.0:50052"
ca = "certs/ca.pem"
sni = "localhost"
tunnel = "tls"

[[nodes]]
id = "50053_tls"
addr = "0.0.0.0:50053"
ca = "certs/ca.pem"
sni = "localhost"
tunnel = "tls"
