[package]
name = "tunnels"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
device = { version = "0.1.0", path = "../device" }
rustls = "0.23.31"
tokio = { version = "1.46.1", features = ["full"] }
tokio-rustls = "0.26.2"
webpki-roots = "1.0.2"
